SimpleHR/Models/Credential.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SimpleHR.Models
{
    public class Credential
    {        
        [Key]
        public string LoginId { get; set; }

        public string PasswordHash { get; set; }

        public ICollection<EmployeeRole> EmployeeRoles; 
    }
}

SimpleHR/Controllers/CredentialsController.cs
using System;
using System.Collections.Generic;
using System.Data;

using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SimpleHR.DataAccess;
using SimpleHR.Models;
using System.Web.Security;
using SimpleHR.Providers;

namespace SimpleHR.Controllers
{
    public class CredentialsController : Controller
    {        
        private ILoginProvider LoginProvider;
        
        public CredentialsController(ILoginProvider provider)
        {
            LoginProvider = provider;
        }

        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]        
        [ValidateAntiForgeryToken]
        public ActionResult Login(Credential model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            else
            {
                if (LoginProvider.ValidateUser(model.LoginId, model.PasswordHash))
                {
                    FormsAuthentication.SetAuthCookie(model.LoginId, false);
                    return RedirectToAction("Index", "Employees");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid login attempt.");
                    return View(model);
                }
            }                     
        }
        
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
        
        public ActionResult Unauthorize()
        {
            return View();
        }
    }
}

SimpleHR/Views/Credentials/Login.cshtml
@using SimpleHR.Models
@model Credential

@{
    ViewBag.Title = "Log in";
}

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Credentials", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4></h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">                    
                    <div class="col-md-2 control-label">Login Id</div>
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.LoginId, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.LoginId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                <div class="form-group">
                    <div class="col-md-2 control-label">Password</div>
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.PasswordHash, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.PasswordHash, "", new { @class = "text-danger" })
                    </div>
                </div>                
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                <hr />
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        Hint:
                    </div>
                    <div class="col-md-offset-2 col-md-10">
                        Use <strong>kevin</strong>/<strong>password</strong> to log in with HR role
                    </div>
                    <div class="col-md-offset-2 col-md-10">
                        Use <strong>Minna_Amigon</strong>/<strong>password</strong> to log in as a regular employee
                    </div>
                    <div class="col-md-offset-2 col-md-10">
                        Use <strong>Donette_Foller</strong>/<strong>password</strong> to log in as a regular employee
                    </div>
                </div>
                @* Enable this once you have account confirmation enabled for password reset functionality
                    <p>
                        @Html.ActionLink("Forgot your password?", "ForgotPassword")
                    </p>*@
            }
        </section>
    </div>
    <div class="col-md-4">
        
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SimpleHR/Views/Credentials/Unauthorize.cshtml
@{
    ViewBag.Title = "Reserved for HR";
}

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-12">
        You are not authorized to take this action.
    </div>  
    <div class="col-md-12">  
        @Html.ActionLink("Back to List", "index", "Employees")
    </div>
</div>